### ISSUE TITLE
Presentasjonen er ødelagt 

### ISSUE THREAD

**Issue by fatso83** [vegarnorman/css#1]
Prøvde å åpne presentasjonen i to forskjellige programmer på min Android. Begge klaget på ugyldig pdf

**Comment by vegarnorman** [comment]
Interessant, skal ta en titt på det. Er laget i Keynote så skulle jo liksom tro eksporteringa fungerte...

**Comment by fatso83** [comment]
Hmm ... testa med Safari nå på mac-en, og det så jo ut til å fungere helt fint. Mulig det er nå bugg med Android.
